### ISSUE TITLE
Two feature suggestions

### ISSUE THREAD

**Issue by a-s-o** [gcanti/cerebral-tcomb#1]
Hello Giulio,

This is a really great project and I look forward to more development. I started integrating this in a couple of pages and quickly ran into some small areas which I fixed with the following two additions:
## 1. Automatic loading or defaults

I have tried to incorporate loaders as described here by Christian (author of cerebral) (http://www.christianalfoni.com/articles/2015_04_26_Handling-complex-state-with-Baobab). See the "Bring state handling to a whole new level" section. Here is how it is implemented:

``` javascript
   function withLoader (type, loader) {
      type.meta.loader = loader;
      return type;
   };
   // Example loader
   function loadDocument (inputs, state) {
      // inputs.path is the full path ['cache', 'documents', 'a123']
      // inputs.lookup is the path after the loader definition ['a123']
      inputs.signals('documentRequested', { id: inputs.lookup[0] });

      // Return default state
      return {
         id: inputs.lookup[0],
         isFetching: true,
         error: null
      };
   }

   const Shape = struct({
      userList: struct({
         isFetching: Bool,
         lastUpdated: maybe(Milliseconds),
         ids: list(Str)
      }),
      cache: struct({
         documents: withLoader(dict(Str, Obj), loadDocuments),  // <- use the loader
         users: withLoader(dict(Str, Obj), loadStaff) 
      })
   });
...
  // In cerebral.onGet
  onGet (target) {
         // Support both string and array path lookups
         const path = _.toPath(target);
         const value = _.get(state, path);
         if (value) return value;

         // Use the loaders if value is not found
         const { loader, loaderIndex } = getType(path);
         if (loader) {
            const inputs = {
               lookup: path.slice(loaderIndex + 1),
               fullPath: path,
               utils: { signals: controller.signals }
            };

            return loader(inputs, state);
         }
      }
```
## 2. Checking whether a state path exists

Useful for checking if a state path exists so that components are not running into undefined state errors.

``` javascript
   controller.hasStatePath = function hasStatePath (target) {
      const { i, len, loader, type } = getType(_.toPath(target));
      if (i < len) {
         if (loader) return true;
         if ((i === len - 1)) {
            switch (type.meta.kind) {
            case 'irreducible': return type.meta.name === 'Obj';
            case 'dict': return true;
            default: return false;
            }
         }
      }
      return !t.Nil.is(type);
   };
```

Example: using the above state tree

``` javascript
   const someComponent = component('UserListViewer', {
      getCursors () {
         return {
            list: ['userLost'] // <- typo will throw an error 
                                // for bad path since it is not in the Shape
         };
      }  
   })
```

---

Both features above are using the following helper:

``` javascript
   function getType (path) {
      let type = Type;
      let loader = Type.meta.loader;
      let loaderIndex = 0;
      let i = 0;
      let len = path.length;
      for (; i < len; i++) {
         if (_.get(type, 'meta.kind') === 'struct') {
            type = _.get(type, ['meta', 'props', path[i]]);
            if (type && type.meta.loader) {
               loader = type.meta.loader;
               loaderIndex = i;
            }
         } else {
            break;
         }
      }
      return { i, len, loader, loaderIndex, type };
   }
```

**Comment by gcanti** [comment]
Hi @a-s-o, 
Great ideas.

**1.**

What about adding a second optional argument to `get`? Like Scala's `Option.getOrElse` method (http://www.scala-lang.org/api/current/index.html#scala.Option).

``` js
get(path: Path, [orElse: (path) => Any])
```

So people could customise the behaviour if a value is not found (i.e `Nil.is(value) === true`). 
For example, in your case, returning a loader.

Seems useful and quite general, maybe it could be added to the official cerebral API?

/cc @christianalfoni

**2.**

If I understand you are proposing a safe `get` API which should leverage the tcomb's meta infos and throw if an invalid path is passed in, right?

Example:

``` js
var State = t.struct({
  email: t.String,
  profile: t.struct({
    age: t.Number
  })
});

var initialState = State({
  email: 'a@domain.com',
  profile: {
    age: 41
  }
});

...

// later...
state.get(['profile', 'name']); // should throw a "Invalid path ['profile', 'name'] supplied to get(path)"
```

**Comment by a-s-o** [comment]
Hi, thanks for taking a look. So, for #1, the reason I suggested the loader method instead of getElse type method is to centralize the logic. If I understand correctly, the get else for will work as follows:

``` javascript
// Suggested getElse form
cerebral.get(['cache', 'documents', 'a123'], cerebral.signals.fetchDocument);
// Is this the same as what we do currently?
const document = cerebral.get(['cache', 'documents', 'a123']);
if (!document) cerebral.signals.fetchDocument('a123');
```

This means that all the places that need a document, all the different components, etc. need to specify the `getElse` option or do the `if (!document)` check and then call the signal. 

The idea with the loaders is that the action "getting document" is general enough that it will not vary too much from one call to the next. The logic is basically as simple as a `GET` request in rest at a specific endpoint with some id. So, in those cases, I would like to specify loader where, if a document is requested and it is not currently in the state, a fetch request gets automatically made. The location making the call does not have to know about `fetchDocument` logic. 

So the same call above with a loader implemented is simply:

``` javascript
const document = cerebral.get(['cache', 'documents', 'a123']);
```

The loader is responsible for fetching, cache invalidation, fetching error (which simply sets and `_fetchingError` metadata flag in my case on the document); the components make the get request above and then react to the state of the document (_isFetching, _fetchingError, _deleted), etc.

**Comment by a-s-o** [comment]
Number 2, is exactly how you said, is to ensure safe access to the state from components. I use it during development to make sure components are not requesting non-existent paths. Having it in the get method implicitly checking on each call would also work.

``` javascript
      if (__DEV__) {
         _.forEach(cursors, (path, key) => {
            if (cerebral.hasStatePath(path) !== true) {
               const str = JSON.stringify({ [key]: path });
               t.fail(`[${componentName}] Invalid state path ${str}`);
            }
         });
      }
```

**Comment by gcanti** [comment]
> is to centralize the logic

Ah.. now I see, sorry I misunderstood your goal. It's not a customisation per request, but a centralized one and my proposal would be really awkward.
Then couldn't it be implemented with a simple wrapper?

``` js
// cerebral-tcomb v0.2 example

const Model = require('cerebral-tcomb');
const t = Model.t;

const State = t.struct({
  ...
});

const initialState = State({
  ...
});

function applyGetMiddleware(model) {
  const next = model.get;
  model.get = function (path) {

    // here intercept and change path if needed

    const value = next(path);
    if (!t.Nil.is(value)) {
      return value;
    }

    // here the custom behaviour

    // Use the loaders if value is not found
    const { loader, loaderIndex } = getType(path);
    ...

  };
  return model;
}

var model = applyGetMiddleware(Model(initialState));
```

**Comment by gcanti** [comment]
> Number 2, is exactly how you said

Perfect, it will be implemented in the next release.

A side note: in your `controller.hasStatePath` implementation you are matching on the type name:

``` js
case 'irreducible': return type.meta.name === 'Obj';
```

It would be more reliable matching on the type constructor:

``` js
case 'irreducible': return type === t.Object;
```

since names are mainly for debugging purposes and are subject to change (actually they are changed in the last releases of tcomb v1.1 and v2.1)

**Comment by a-s-o** [comment]
Okay, thanks for that tip. You're right about the middleware approach. Thanks for the pattern I will use that.

**Comment by a-s-o** [comment]
Additionally, may I request exposing a getType like method on the controller. I presume you will be using it internally to verify a path exists. That way it is available for other uses (like hasStatePath or loader middleware)

**Comment by christianalfoni** [comment]
Hi guys,

Just wanted to mention that it will be great to see how this works out. When we have some experience I would love to discuss bringing ideas into the official Cerebral API :-)

**Comment by gcanti** [comment]
> Additionally, may I request exposing a getType like method on the controller

@a-s-o Ok, no problem but what you mean by "controller" ? I can add that method to the model:

``` js
const Model = require('cerebral-tcomb');

const State = t.struct({
  ...
});

const initialState = State({
  ...
});

var model = Model(initialState);
model.getType(); // => State constructor
```

I'm not able to change the `controller` interface here:

``` js
var Controller = require('cerebral');
var controller = Controller(Model(initialState)); // <= controller interface is determined by the cerebral package
```

**Comment by a-s-o** [comment]
Right, please add it to the model. I was still speaking in terms of cerebral <v0.16 where the model could define additional methods on the controller. `model.getType(path)` would be just fine.
