### ISSUE TITLE
Checking whether a state path exists

### ISSUE THREAD

**Issue by gcanti** [gcanti/cerebral-tcomb#2]
a safe `get` API which should leverage the tcomb's meta infos and throw if an invalid path is passed in.

**Example**

``` js
var State = t.struct({
  email: t.String,
  profile: t.struct({
    age: t.Number
  })
});

var initialState = State({
  email: 'a@domain.com',
  profile: {
    age: 41
  }
});

...

// later...
state.get(['profile', 'name']); // should throw a "Invalid path ['profile', 'name'] supplied to get(path)"
```

**Comment by gcanti** [comment]
Hi @a-s-o,
just published v0.2.1 with the new feature. Let me know how it goes

**Comment by a-s-o** [comment]
Hi Giulio,

Just upgraded to the new version. Works great, thanks for implementing this.

**Comment by gcanti** [comment]
Great. Thanks for your feedback
