### ISSUE TITLE
expose a getType method on the controller

### ISSUE THREAD

**Issue by gcanti** [gcanti/cerebral-tcomb#3]

**Comment by gcanti** [comment]
@a-s-o

Sorry but I'm confused. Let's recap in this new issue:

I can add the method `getType()` to the model...

``` js
const Model = require('cerebral-tcomb');

const State = t.struct({
  ...
});

const initialState = State({
  ...
});

var model = Model(initialState);
model.getType(); // => State constructor

// getType could just be defined here
model.getType = function () {
  return State;
};
```

..or to the state:

``` js
controller.signal('test', function (input, state, output) {
  state.getType(): // => State constructor
});
```

Though in the first case I can't see how it could be useful since normally the model is swallowed by the controller:

``` js
var controller = Controller(Model(initialState));
```

**Comment by a-s-o** [comment]
Hi, the current syntax for cerebral models does make it hard to do. Here is how I am doing it

``` javascript
   function modelFactory (controller) {
      const Model = require('cerebral-tcomb')(State({ /*initial state*/ }));
      const model = Model(controller);

      model.get = _.wrap(model.get, function wrapped$get (next, path) {
         const value = next(path);
         if (!t.Nil.is(value)) return value;

         const type = model.getType(path);  // Need to access getType here
         if (type.loader) {
            ...
         }
      });

      // Also
      controller.hasStatePath = function hasStatePath (path) {
          const type = model.getType();
      };   

      return model;
   }

   const controller = require('cerebral')(modelFactory, defaultInput);
```

**Comment by a-s-o** [comment]
Having said that, thanks so much for your help but if you don't find this method useful, you can skip this as well. I don't mind writing it myself since I have access to the original state Type. It seems like a very specific case to me and no point in increasing the api of this package

**Comment by gcanti** [comment]
> It seems like a very specific case to me and no point in increasing the api of this package

I think you are right, I'll leave it out for now. Thanks for the clarification.
